name: CI/CD Airflow with Astro

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Astro CLI
        run: curl -sSL https://install.astronomer.io | sudo bash
      - name: Lint DAGs
        run: astro dev lint
      - name: Run DAG tests
        run: astro dev pytest tests/

  docker-build-push:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Astro Airflow image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/airflow-marketing:latest
          astro dev build --tag $IMAGE_URI
          docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy with ECS
        run: |
          aws ecs update-service \
            --cluster marketing-cluster \
            --service airflow-service \
            --force-new-deployment
